include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Bật các rule kiểm tra const
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    prefer_const_declarations: true

    # (Tuỳ chọn) Một số rule hữu ích khác
    avoid_unnecessary_containers: true
    unnecessary_this: true
    sort_child_properties_last: true
